spring:
  application:
    name: spring-ai-embabel
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    mcp:
      server:
        protocol: STREAMABLE
  swagger-ui:
    path: /swagger-ui.html
embabel:
  models:
    default-llm: gpt-4.1-mini
    llms:
      cheapest: gpt-4.1-mini
      best: gpt-4.1
boardgame:
  rules:
    path: gamerules
server:
  port: 8080

